# Generated by Django 3.0.7 on 2020-11-01 12:38

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnote',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='classnote',
            name='title',
            field=models.CharField(max_length=47),
        ),
    ]
